# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         VFSsimple-Drv-Iso
version:      0.01
version_from: lib/VFSsimple/Drv/Iso.pm
installdirs:  site
requires:
    Device::Cdio::ISO9660:         

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
